version: '3'
services:
  db:
    image: robertfraefel/pm_backend:latest
    restart: always
    container_name: pm_backend
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8081:8080
