version: '3.9'

services:
  db:
    image: mysql:latest
    restart: always
    container_name: pm_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: power4ever
      MYSQL_DATABASE: powermanager
      MYSQL_USER: powermanager
      MYSQL_PASSWORD: power4ever
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db_data:
