version: '3.9'

services:
  db:
    image: robertfraefel/pm_backend:latest
    restart: always
    container_name: pm_backend
    
  app:
#    build:
#      context: .
#      args:
#        - DATABASE_HOST=192.168.1.44
#        - DATABASE_PORT=3306
#        - DATABASE_NAME=powermanager
  
#    volumes:
#      - pm_backend_data:/var/lib/pm_data
    ports:
      - 8081:8080

#volumes:
#  pm_backend_data:
