version: '3'
services:
  app:
    image: robertfraefel/pm_backend:latest
    container_name: pm_backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.1.44:3306/power_manager?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=power4ever
    volumes:
      - logs:/powermanager_logs
    ports:
      - 8081:8080
volumes:
  logs:
